definitions:
  entity.Answer:
    properties:
      contact:
        type: string
      content:
        type: string
      create_at:
        type: string
      ext_msg:
        type: string
      finger:
        type: string
      id:
        type: integer
      ip:
        type: string
      label:
        type: string
      question_id:
        type: integer
      survey_id:
        type: integer
    type: object
  entity.Option:
    properties:
      has_ext_msg:
        type: string
      id:
        type: integer
      label:
        type: string
      question_id:
        type: integer
      survey_id:
        type: integer
      value:
        type: string
    type: object
  entity.Question:
    properties:
      id:
        type: integer
      options:
        items:
          $ref: '#/definitions/entity.Option'
        type: array
      order:
        type: integer
      survey_id:
        type: integer
      text:
        type: string
      type:
        type: string
    type: object
  entity.Survey:
    properties:
      description:
        type: string
      end_time:
        type: string
      id:
        type: integer
      need_contact:
        type: string
      questions:
        items:
          type: integer
        type: array
      repeat:
        description: 是否允许重复提交 no yes yes_but_update
        type: string
      repeat_check:
        description: 重复提交检查方式 finger contact
        type: string
      start_time:
        type: string
      status:
        type: string
      title:
        type: string
      water_mark:
        description: 水印
        type: string
    type: object
info:
  contact: {}
  title: 问卷调查SurveyX API
  version: "1.0"
paths:
  /answer/:
    post:
      consumes:
      - application/json
      description: 添加答案
      parameters:
      - description: 答案
        in: body
        name: answer
        required: true
        schema:
          items:
            $ref: '#/definitions/entity.Answer'
          type: array
      produces:
      - application/json
      responses: {}
      summary: 添加
      tags:
      - 答案
  /login:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - description: key
        in: body
        name: key
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses: {}
      summary: 登录
      tags:
      - 公共
  /question/:
    post:
      consumes:
      - application/json
      description: 添加题目
      parameters:
      - description: 题目
        in: body
        name: question
        required: true
        schema:
          $ref: '#/definitions/entity.Question'
      produces:
      - application/json
      responses: {}
      summary: 添加
      tags:
      - 题目
    put:
      consumes:
      - application/json
      description: 更新题目
      parameters:
      - description: 题目
        in: body
        name: question
        required: true
        schema:
          $ref: '#/definitions/entity.Question'
      produces:
      - application/json
      responses: {}
      summary: 更新
      tags:
      - 题目
  /question/{id}:
    delete:
      description: 删除题目
      produces:
      - application/json
      responses: {}
      summary: 删除
      tags:
      - 题目
    get:
      description: 获取题目
      produces:
      - application/json
      responses: {}
      summary: 获取
      tags:
      - 题目
  /question/list:
    get:
      description: 获取题目列表列表
      parameters:
      - description: 关键字
        in: query
        name: keyword
        type: string
      - description: 页码
        in: query
        name: pageNum
        type: integer
      - description: 每页大小
        in: query
        name: pageSize
        type: integer
      - description: 题目id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 题目列表
      tags:
      - 题目
  /survey/:
    post:
      consumes:
      - application/json
      description: 添加问卷
      parameters:
      - description: 问卷
        in: body
        name: survey
        required: true
        schema:
          $ref: '#/definitions/entity.Survey'
      produces:
      - application/json
      responses: {}
      summary: 添加
      tags:
      - 问卷
    put:
      consumes:
      - application/json
      description: 更新问卷
      parameters:
      - description: 问卷
        in: body
        name: survey
        required: true
        schema:
          $ref: '#/definitions/entity.Survey'
      produces:
      - application/json
      responses: {}
      summary: 更新
      tags:
      - 问卷
  /survey/{id}:
    delete:
      description: 删除问卷
      parameters:
      - description: 问卷id
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      summary: 删除
      tags:
      - 问卷
    get:
      consumes:
      - application/json
      description: 获取获取
      parameters:
      - description: 题目id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 获取
      tags:
      - 问卷
  /survey/list:
    get:
      description: 获取问卷列表
      parameters:
      - description: 关键字
        in: query
        name: keyword
        type: string
      - description: 页码
        in: query
        name: pageNum
        type: integer
      - description: 每页大小
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 问卷列表
      tags:
      - 问卷
swagger: "2.0"
