db :
  sqlType : sqlite  # mysql || sqlite || postgres
  sqlUrl: survey.db
  #sqlUrl : username:password@tcp(host:port)/database?charset=utf8mb4&parseTime=True&loc=Local #mysql
  #sqlUrl : postgres://default:s8kKoq3BfrFv@ep-bold-bird-66330765-pooler.ap-southeast-1.postgres.vercel-storage.com:5432/verceldb  #postgres


port : 65534

oauth:
  clientId : ff3f2aa615877bd961e7
  clientSecret : 84f840226a1fe34990e4725d9040fa9e6086da36
