// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/sxz799/surveyX/config"
	"github.com/sxz799/surveyX/utils"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeServer() (*ServerDeps, error) {
	configConfig := config.NewConfig()
	db := utils.InitDB(configConfig)
	serverDeps := &ServerDeps{
		DB:     db,
		Config: configConfig,
	}
	return serverDeps, nil
}

// wire.go:

// ServerDeps 包含所有服务器依赖
type ServerDeps struct {
	DB     *gorm.DB
	Config *config.Config
}
