name: CI

on:
  push:
    branches: [dev]

jobs:
  build-web:
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Build Web
      run: |
        sed -i '9s|//||' vite.config.js
        npm install && npm run build
      working-directory: ./web
      
    - name: Upload Artifact-Web
      uses: actions/upload-artifact@v2
      with:
       name: suveryX-artifact-web
       path: ${{ github.workspace }}

  build-linux:
    needs: build-web
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
    - uses: actions/checkout@v3

    - name: intall deps
      run: |
        yum install -y wget tar gcc automake autoconf libtool make

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Build Server for Linux
      run: go build -ldflags="-s -w" -o bin/app_linux .
      working-directory: ./server

    - name: Copy  Files
      run: |
        mkdir suveryX_Linux
        cp -r server/conf.yaml suveryX_Linux/
        cp -r server/bin/app_linux suveryX_Linux/
        cp -r dist suveryX_Linux/
        
    - name: Upload Artifact-Linux
      uses: actions/upload-artifact@v2
      with:
       name: suveryX-artifact-linux
       path: ${{ github.workspace }}/suveryX_Linux

    - name: Download a Build Artifact-Linux
      uses: actions/download-artifact@v2.1.1
      with:
       name: suveryX-artifact-linux

    
