name: CI

on:
  push:
    branches: [main]

jobs:
  build-web:
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Build Web
      run: |
        sed -i '9s|//||' vite.config.js
        npm install && npm run build
      working-directory: ./web
      
    - name: Move Files
      run: |
        mkdir suveryX_WEB
        tar -czf suveryX-artifact-web.tar.gz web/dist
        mv suveryX-artifact-web.tar.gz suveryX_WEB/
      
    - name: Upload Artifact-Web
      uses: actions/upload-artifact@v2
      with:
       name: suveryX-artifact-web
       path: ${{ github.workspace }}/suveryX_WEB

  build-linux:
    needs: build-web
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
    - uses: actions/checkout@v3

    - name: intall deps
      run: |
        yum install -y wget tar gcc automake autoconf libtool make

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Build Server for Linux
      run: go build -ldflags="-s -w" -o bin/app_linux .
      working-directory: ./server

    - name: Download Web Artifact
      uses: actions/download-artifact@v2.1.1
      with:
       name: suveryX-artifact-web

    - name: Copy Files
      run: |
        mkdir suveryX_Linux
        tar xzf suveryX-artifact-web.tar.gz -C .
        cp -r web/dist suveryX_Linux/
        cp -r server/conf.yaml suveryX_Linux/
        cp -r server/bin/app_linux suveryX_Linux/

    - name: Upload Artifact-Linux
      uses: actions/upload-artifact@v2
      with:
       name: suveryX-artifact-linux
       path: ${{ github.workspace }}/suveryX_Linux

    - name: Download a Build Artifact-Linux
      uses: actions/download-artifact@v2.1.1
      with:
       name: suveryX-artifact-linux

  build-mac:
    needs: build-web
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Build Server for Mac
      run: go build -ldflags="-s -w" -o bin/app_mac .
      working-directory: ./server

    - name: Download Web Artifact
      uses: actions/download-artifact@v2.1.1
      with:
       name: suveryX-artifact-web

    - name: Copy Files
      run: |
        mkdir suveryX_Mac
        tar xzf suveryX-artifact-web.tar.gz -C .
        cp -r web/dist suveryX_Mac/
        cp -r server/conf.yaml suveryX_Mac/
        cp -r server/bin/app_mac suveryX_Mac/

    - name: Upload Artifact-Mac
      uses: actions/upload-artifact@v2
      with:
       name: suveryX-artifact-mac
       path: ${{ github.workspace }}/suveryX_Mac

    - name: Download a Build Artifact-Mac
      uses: actions/download-artifact@v2.1.1
      with:
       name: suveryX-artifact-mac

  build-windows:
    needs: build-web
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Build Server for Windows
      run: go build -ldflags="-s -w" -o bin/app_windows.exe .
      working-directory: ./server

    - name: Download Web Artifact
      uses: actions/download-artifact@v2.1.1
      with:
       name: suveryX-artifact-web

    - name: Copy Files
      run: |
        mkdir suveryX_Windows
        tar xzf suveryX-artifact-web.tar.gz -C .
        cp -r web/dist suveryX_Windows/
        cp -r server/conf.yaml suveryX_Windows/
        cp -r server/bin/app_windows.exe suveryX_Windows/

    - name: Upload Artifact-Windows
      uses: actions/upload-artifact@v2
      with:
       name: suveryX-artifact-windows
       path: ${{ github.workspace }}/suveryX_Windows

    - name: Download a Build Artifact-Windows
      uses: actions/download-artifact@v2.1.1
      with:
       name: suveryX-artifact-windows
